'use strict';

import CaseTeam from '@cafienne/typescript-client/cmmn/team/caseteam';
import CaseTeamUser, { CaseOwner } from "@cafienne/typescript-client/cmmn/team/caseteamuser";
import CaseService from '@cafienne/typescript-client/service/case/caseservice';
import DebugService from '@cafienne/typescript-client/service/case/debugservice';
import RepositoryService from '@cafienne/typescript-client/service/case/repositoryservice';
import StartCase from '@cafienne/typescript-client/service/case/startcase';
import CafienneResponse from '@cafienne/typescript-client/service/response';
import TestCase from '@cafienne/typescript-client/test/testcase';
import { SomeTime } from '@cafienne/typescript-client/test/time';
import WorldWideTestTenant from '../../worldwidetesttenant';

const definition = 'caseteam.xml';

const tenant = Math.random().toString(36).substring(7);
const worldwideTenant = new WorldWideTestTenant(tenant);
const sender = worldwideTenant.sender;
export default class TestInvalidStartCase extends TestCase {
    async onPrepareTest() {
        await worldwideTenant.create();
        await RepositoryService.validateAndDeploy(sender, definition, tenant);
    }

    startCase: StartCase = { tenant, definition, debug: true };

    async run() {

        const startCase = this.startCase;

        // Case team without owner
        startCase.caseTeam = new CaseTeam([new CaseTeamUser(sender)]);
        await this.tryStartCase("Missing owner should fail");

        // Case team with invalid roles
        startCase.caseTeam = new CaseTeam([new CaseOwner(sender, ["ADMIN", "Not-Exisitng-CaseRole-Not-Allowed-In-Team"])]);
        await this.tryStartCase("Invalid roles should fail");

        // TODO: add a check for invalid member type in the backend??
        // Case team with invalid member type
        // startCase.caseTeam = new CaseTeam([new CaseOwner(sender, [], 'wrong-type')]);
        // await this.tryStartCase("Wrong member type should fail");

        // Remove case team, sender would become member and owner of the new case to be started (if that ever succeeds ...)
        delete startCase.caseTeam;

        // Invalid format of case instance id
        startCase.caseInstanceId = 'Ueè';
        await this.tryStartCase(`Invalid case instance id '${startCase.caseInstanceId}' should fail`);

        // Using tenant id as case instance id should fail. tenant is 'World-Wide-Test-Tenant'
        startCase.caseInstanceId = tenant;
        await this.tryStartCase(`Using tenant id as case instance id '${startCase.caseInstanceId}' should fail`);

        // Force tenant recovery and then try again, again it should fail. This validates the recovery in combination first command in different type of model actor
        await DebugService.forceRecovery(sender, tenant);
        await SomeTime(1000, 'Waiting for the tenant to go out-of-memory');
        await this.tryStartCase(`Using tenant id as case instance id '${startCase.caseInstanceId}' should fail`);


        // Remove invalid case instance id and let it be generated by server
        delete startCase.caseInstanceId;

        // Wrong tenant should fail
        startCase.tenant = 'not-existing-tenants';
        await this.tryStartCase(`Wrong tenant should fail with 404`, 404);

        startCase.tenant = tenant;

        // Wrong input should fail
        startCase.inputs = { 'not-existing-input-parameter': 123 };
        await this.tryStartCase(`Wrong inputs should fail`);

        // Remove definition should make it fail
        delete startCase.definition;
        await this.tryStartCase(`Missing case definition should fail`);
    }

    async tryStartCase(msg: string, expectedResponseCode: number = 400) {
        console.log('\n============\n' + msg);
        const response = await CaseService.startCase(sender, this.startCase, expectedResponseCode, msg)
        if (response instanceof CafienneResponse) {
            await response.text().then(response => console.log("Response text: " + response));
        }
    }
}
