import Tenant from "../../tenant/tenant";
import User from "../../user";
import ConsentGroupMember from "./consentgroupmember";

export default class ConsentGroup {
    public id?: string;

    /**
     * Simple wrapper class for ConsentGroup.
     * @param members List group members
     * @param groupId Optional identifier of the group. Will be generated by the server if it is omitted.
     */
    constructor(public members: Array<ConsentGroupMember> = [], groupId: string = '') {
        this.id = groupId;
    }

    toJson() {
        const id = this.id;
        const members = this.members.map(member => (member.toJson) ? member.toJson() : member);
        return { id, members };
    }

    /**
     * Returns the tenant users that are owner.
     */
    getOwners() {
        return this.members.filter(user => user.isOwner);
    }

    /**
     * Returns true if the member with the specified id can be found in this group.
     * @param identifier
     * @returns 
     */
    hasMember(identifier: string | User): boolean {
        return this.members.find(m => m.id === identifier.toString() || m.userId === identifier.toString()) !== undefined;
    }

    /**
     * Returns the member with the specified name.
     * @param identifier
     * @returns 
     */
    getMember(identifier: string | User): ConsentGroupMember {
        const member = this.members.find(m => m.id === identifier.toString() || m.userId === identifier.toString());
        if (member) {
            return member;
        } else {
            throw new Error(`Member '${identifier}' is not present in the list of members'`);
        }
    }

    toString() {
        return this.id;
    }
}
